%% Plot Isometric Extension Example Results
%==========================================================================
close all;
import org.opensim.modeling.*

line_width = 2;

[states_data, states_labels, states_header] = read_opensim_mot('../results/forsim/isometric_extension_states.sto');
states_time = states_data(:,1);

%% Plot All Knee Kinematics
tf_coords = {...
    '/jointset/knee_r/knee_flex_r/value';...
    '/jointset/knee_r/knee_add_r/value';...
    '/jointset/knee_r/knee_rot_r/value';...
    '/jointset/knee_r/knee_tx_r/value';...
    '/jointset/knee_r/knee_ty_r/value';...
    '/jointset/knee_r/knee_tz_r/value';...
    };


figure('name','Tibiofemoral Kinematics')
hold on;
for i = 1:length(tf_coords)
    ind = find(contains(states_labels,tf_coords{i}));
    subplot(3,2,i);hold on;
    plot(states_time,states_data(:,ind),'b','LineWidth',line_width)   
    title(tf_coords{i})
end

pf_coords = {...
    '/jointset/pf_r/pf_flex_r/value';...
    '/jointset/pf_r/pf_rot_r/value';...
    '/jointset/pf_r/pf_tilt_r/value';...
    '/jointset/pf_r/pf_tx_r/value';...
    '/jointset/pf_r/pf_ty_r/value';...
    '/jointset/pf_r/pf_tz_r/value';...
    };
figure('name','Patellofemoral Kinematics')
hold on;
for i = 1:length(pf_coords)
    ind = find(contains(states_labels,pf_coords{i}));
    subplot(3,2,i);hold on;
    plot(states_time,states_data(:,ind),'b','LineWidth',line_width)    
    title(pf_coords{i})
end